spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/realms/E-Commerce-Microservices-security-realm"
server:
  port: 9000
