spring:
  application:
    name: Order-Service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081
