spring:
  application:
    name: Order-Service
  datasource:
    url: jdbc:mysql://localhost:3316/order_service
    username: root
    password: mysql
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8081
