spring:
  application:
    name: Product-Service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080