spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: mysql
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082